### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Svengali** [fuchstraumer/DiamondDogs#1]
(As an aside, I couldnt find a contact email for you, besides your UW email, so I decided to put this here)

I love your Vulpes renderer and am going to use your DiamondDogs project as a starting point to bring my code over to use Vulkan.  Im going to fork, Vulpes (and hopefully contribute back in the same style), and only use DiamonDogs as a reference.  

However, DD has no license, so I cannot even use it as a reference.  Im guessing thats an oversight, vs keeping it private, but legally I have to assume you dont want to release it.

**Comment by fuchstraumer** [comment]
Whoa, awesome! I had no idea someone thought VPR/VulpesRender was worth using :)

This is definitely an oversight. I'll update the license shortly. What parts are you using for reference in particular? I have sources that shaped the code I made for the two main portions, the star and terrain rendering stuff that I'd be happy to share. 

Please make sure to log bugs or issues you see in VPR as well (allocator subsystem can be a bit odd atm), as it's recently been retooled and I hope the newer version of it (as a group of primitives) works for you. If you still want the scene stuff, that's now over in VulpesSceneKit (vpsk) which itself is in the middle of some rather serious work to change how I do things.

Really happy to know that someone likes me work enough to use it, so I'm more than happy to assist any way I can :D

**Comment by fuchstraumer** [comment]
Closed after latest commit adding license file :)

**Comment by Svengali** [comment]
:)  For me, its very similar to my own natural style of programming.  The feature list is perfect, so I can add my own higher level engine parts like event components.  Unlike a lot of the tutorials its coherent.  

Either project would probably be fine for me for now.  Right now Im just interested in getting the first triangle round trip and those sorts of things.  Later Ill have more opinions / comments on things.  

I will happily report/fix any bugs I find of course.  

For scenes, I would have to look at it.  I tend to use my own layers above 'RenderMesh', since it depends on what kind of ECS Im using, what kind of game it is, etc.  

For my own internal code, Ive moved into using Expected/Option/Maybe heavily.  I find its a very clean way to report back errors.  Unsure of your opinion on that.

**Comment by fuchstraumer** [comment]
Most of the code in this repo is fairly old and dated, to be honest - I haven't had time to work on it, and most of my work on my other repos is because I use those as the graphics backend for work projects. With respect to Expected/Option/Maybe - I've thought about systems like this in the past, but didn't consider it for VPR as I'd like to eventually get the interface to VPR simple enough to work as a dynamic library. And unfortunately, that can mean discarding a lot of the nice features and complexity of C++ :(

In regards to the first triangle tests, I have a "demoscene" for this in VPSK - though only things I think you might have use for are the shaders and some of the commands being used:
https://github.com/fuchstraumer/VulpesSceneKit/blob/master/demoscenes/Triangle.cpp

The BaseScene class is here:
https://github.com/fuchstraumer/VulpesSceneKit/blob/master/include/scene/BaseScene.hpp
https://github.com/fuchstraumer/VulpesSceneKit/blob/master/src/scene/BaseScene.cpp

I can understand (and agree with, BaseScene is on its way out) not using stuff this abstract right off the bat, but if nothing else it least provides an outline of basic renderpass setup, command submission, and command pool creation. I probably habitually set the viewport and scissor through dynamic states too much, but that's easily changed. There are a few other scenes that show off slightly more advanced techniques, too. Sascha's examples are where I get a good chunk of my stuff, the rest is from reading the official Vulkan guide and blogs like [this one](http://kylehalladay.com/), and [this one](http://ourmachinery.com/). A recently notable repo I've found is [this one](https://github.com/Themaister/Granite), which is a considerably higher-level Vulkan renderer that implements a rendergraph system detailed in [this blogpost](http://themaister.net/blog/2017/08/15/render-graphs-and-vulkan-a-deep-dive/).

That's a ton of looking through stuff to do, and the last one might not be what you're looking for - but better to share the resources and not need them than to not share and have them be needed eventually :D
